/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universityapp;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author satranga
 */
public class HomePanel extends javax.swing.JPanel {
    private int panelNum;
    /**
     * Creates new form HomeScreen
     */
    public HomePanel() {
        initComponents();
        this.panelNum = 0;
        this.buttonPanel.setOpaque(false);
        
    }

    public int getNum(){
        return panelNum;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        collegeButton = new javax.swing.JButton();
        calendarButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));

        collegeButton.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        collegeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universityapp/GradFinalFinal.png"))); // NOI18N
        collegeButton.setText("          My Colleges");
        collegeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        collegeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegeButtonActionPerformed(evt);
            }
        });

        calendarButton.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        calendarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universityapp/FinalCalendar.png"))); // NOI18N
        calendarButton.setText("          My Calendar");
        calendarButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        calendarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(collegeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calendarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE))
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(calendarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(collegeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(buttonPanel);
        buttonPanel.setBounds(110, 120, 820, 330);

        titleLabel.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("THE COLLEGE APPLICATION");
        add(titleLabel);
        titleLabel.setBounds(180, 30, 660, 56);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universityapp/UCBerkeleyCampus.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(-4, -4, 1010, 610);
    }// </editor-fold>//GEN-END:initComponents

    private void calendarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarButtonActionPerformed
        ((MainFrame)this.getRootPane().getParent()).showPanel(1);
    }//GEN-LAST:event_calendarButtonActionPerformed

    private void collegeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegeButtonActionPerformed
        ((MainFrame)this.getRootPane().getParent()).showPanel(2);
    }//GEN-LAST:event_collegeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton calendarButton;
    private javax.swing.JButton collegeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
