/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universityapp;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author satranga
 */
public class MainFrame extends javax.swing.JFrame {
    //Final dimensions of JFrame
    public static final int PANEL_WIDTH = 1000;
    public static final int PANEL_HEIGHT = 600;
    public static final int PANEL_X = 0;
    public static final int PANEL_Y = 0;
    /**
     * Creates new form MainFrame
     */
    public ArrayList<JPanel> screens;


    public MainFrame() throws FileNotFoundException {
        initComponents();
        
        //Frame Setup
        this.setSize(PANEL_WIDTH, PANEL_HEIGHT);
        this.setLocation(PANEL_WIDTH, PANEL_HEIGHT);
        this.setResizable(false);
        
        //MultiplePanelCode
        createPanels();
        this.pack();
    }
    
    
    
   
    
    public void createPanels() throws FileNotFoundException{
        //ArrayList stores JPanels for easy navigation
        this.screens = new ArrayList<JPanel>();        

        //HomePanel Initialization
        HomePanel p1 = new HomePanel();
        p1.setSize(this.getContentPane().getWidth(), this.getContentPane().getHeight());
        p1.setLocation(PANEL_X, PANEL_Y);
        screens.add(p1);
        this.add(p1);
        //Serves as start screen
        p1.setVisible(true);        

        //My Calendar Initialization
        CalendarPanel p2 = new CalendarPanel();
        p2.setSize(PANEL_WIDTH, PANEL_HEIGHT);
        p2.setLocation(PANEL_X, PANEL_Y);
        screens.add(p2);
        this.add(p2);
        p2.setVisible(false);

        //My Colleges Initialization
        CollegesPanel p3 = new CollegesPanel();
        p3.setSize(PANEL_WIDTH, PANEL_HEIGHT);
        p3.setLocation(PANEL_X, PANEL_Y);
        screens.add(p3);
        this.add(p3);
        p3.setVisible(false);
        
        this.pack();
    }
    //Sets an individual JPanel, the parameter, as visible
    public void showPanel(int panelNum) {
        for (int i = 0; i < screens.size(); i++) {
            screens.get(i).setVisible(false);;
        }
        screens.get(panelNum).setVisible(true);
    }
    
    public static ArrayList loadFrom(String fileName) throws FileNotFoundException {
        GsonBuilder builder = new GsonBuilder();
        builder.setPrettyPrinting();
        Gson gson = builder.create();
//        return gson.fromJson(new FileReader(fileName), Database.class);
        return null;
    }
    
    public static void saveTo(String fileName, ArrayList list) throws IOException {
        GsonBuilder builder = new GsonBuilder();
        builder.setPrettyPrinting();
        Gson gson = builder.create();
        for (int i = 0; i < list.size(); i++) {
            try (FileWriter writer = new FileWriter(fileName)) {
            gson.toJson(list.get(i), writer);
            }
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                
            }
        });
        
        
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
